// Class visual + descriptive metadata. Lifted from v2 file unchanged.

export const classData = {
  Artificer: {
    color: "bg-[#d85a24] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#8e2c1a]",
    motto: "Power through tools, invention, repair, and applied systems.",
    summary: "You turn ideas into working things. You build, automate, repair, prototype, script, engineer, and make abstract knowledge usable in the real world.",
    traits: ["Tool Builder", "Applied Technical", "Prototype Mind"],
  },
  Barbarian: {
    color: "bg-[#c7381d] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#8e2c1a]",
    motto: "Power through pressure, instinct, and raw courage.",
    summary: "You are at your strongest when the situation gets intense. You move toward pressure instead of away from it, and your strength is protective, emotional, and immediate.",
    traits: ["Pressure Brave", "Protective Force", "Explosive Energy"],
  },
  Bard: {
    color: "bg-[#ef7a32] text-[#171717] border-[#0b0b0b]",
    accent: "text-[#c7381d]",
    motto: "Power through expression, influence, and shared emotion.",
    summary: "You change the room. Through humor, music, teaching, storytelling, performance, or social skill, your gift is turning attention into momentum.",
    traits: ["Story Shaper", "Social Spark", "Creative Influence"],
  },
  Cleric: {
    color: "bg-[#fff2cf] text-[#171717] border-[#0b0b0b]",
    accent: "text-[#d85a24]",
    motto: "Power through devotion, service, and sacred responsibility.",
    summary: "You are driven by care, calling, and service. Your strength comes from helping people heal, endure, and reconnect with something larger than themselves.",
    traits: ["Community Healer", "Devoted Guide", "Steady Light"],
  },
  Druid: {
    color: "bg-[#168a32] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#0d5521]",
    motto: "Power through nature, balance, and living systems.",
    summary: "You feel oriented by nature and living systems. Your instincts lean toward stewardship, ecology, animals, plants, cycles, and balance.",
    traits: ["Nature Bound", "Balance Keeper", "Living Systems Mind"],
  },
  Fighter: {
    color: "bg-[#727a78] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#4d5554]",
    motto: "Power through training, discipline, and repeatable skill.",
    summary: "You respect craft. You build competence through drills, systems, tools, and practice until your skill works under pressure.",
    traits: ["Trained Operator", "Tactical Builder", "Reliable Specialist"],
  },
  Monk: {
    color: "bg-[#f1c4a8] text-[#171717] border-[#0b0b0b]",
    accent: "text-[#d85a24]",
    motto: "Power through discipline, body control, and inner focus.",
    summary: "You are strongest when body and mind work together. Your path is discipline, self regulation, martial practice, breath, restraint, and focused repetition.",
    traits: ["Body Mind Discipline", "Calm Under Strain", "Focused Practice"],
  },
  Paladin: {
    color: "bg-[#8ddfd6] text-[#171717] border-[#0b0b0b]",
    accent: "text-[#2e7f82]",
    motto: "Power through oath, duty, and moral action.",
    summary: "You are not just motivated. You are committed. Your identity sharpens around causes, promises, standards, and action when something important is on the line.",
    traits: ["Oath Driven", "Moral Protector", "Mission Leader"],
  },
  Ranger: {
    color: "bg-[#0d5521] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#168a32]",
    motto: "Power through fieldcraft, tracking, and practical independence.",
    summary: "You are observant, practical, and comfortable operating away from the crowd. You notice terrain, patterns, movement, risks, and resources before others do.",
    traits: ["Field Ready", "Quiet Watcher", "Practical Survivor"],
  },
  Rogue: {
    color: "bg-[#2b2f31] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#727a78]",
    motto: "Power through cunning, precision, and alternate routes.",
    summary: "You solve problems by seeing the side door. You are precise, adaptive, skeptical of obvious paths, and good at turning limited information into advantage.",
    traits: ["Side Door Thinker", "Precision Mover", "Information Edge"],
  },
  Sorcerer: {
    color: "bg-[#8e2c1a] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#c7381d]",
    motto: "Power through innate gift, charisma, and natural force.",
    summary: "Some of what you do well seems to come naturally. You often rely on instinct, presence, raw aptitude, or personal magnetism before formal systems catch up.",
    traits: ["Natural Talent", "Raw Spark", "Instinctive Power"],
  },
  Warlock: {
    color: "bg-[#4d5554] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#2b2f31]",
    motto: "Power through patronage, leverage, and rare access.",
    summary: "You understand that power often comes through networks, institutions, sponsors, mentors, contracts, platforms, and access. You are good at using leverage others overlook.",
    traits: ["Patron Linked", "Access Broker", "Leverage Mind"],
  },
  Wizard: {
    color: "bg-[#c5cbc7] text-[#171717] border-[#0b0b0b]",
    accent: "text-[#2e7f82]",
    motto: "Power through study, systems, and documented mastery.",
    summary: "You turn knowledge into capability. You research, document, compare, prepare, and build mental models until a confusing problem becomes a usable system.",
    traits: ["Scholar Builder", "Systems Thinker", "Prepared Mind"],
  },
};

export const scoreBarColors = {
  Artificer: "bg-[#d85a24]",
  Barbarian: "bg-[#c7381d]",
  Bard: "bg-[#ef7a32]",
  Cleric: "bg-[#fff2cf]",
  Druid: "bg-[#168a32]",
  Fighter: "bg-[#727a78]",
  Monk: "bg-[#f1c4a8]",
  Paladin: "bg-[#8ddfd6]",
  Ranger: "bg-[#0d5521]",
  Rogue: "bg-[#2b2f31]",
  Sorcerer: "bg-[#8e2c1a]",
  Warlock: "bg-[#4d5554]",
  Wizard: "bg-[#c5cbc7]",
};

export const classIconSrc = {
  Artificer: "class-icons/artificer.png",
  Barbarian: "class-icons/barbarian.png",
  Bard: "class-icons/bard.png",
  Cleric: "class-icons/cleric.png",
  Druid: "class-icons/druid.png",
  Fighter: "class-icons/fighter.png",
  Monk: "class-icons/monk.png",
  Paladin: "class-icons/paladin.png",
  Ranger: "class-icons/ranger.png",
  Rogue: "class-icons/rogue.png",
  Sorcerer: "class-icons/sorcerer.png",
  Warlock: "class-icons/warlock.png",
  Wizard: "class-icons/wizard.png",
};

export const subclassData = {
  Artificer: {
    Alchemist: "You transform problems through experiments, mixtures, chemistry, support, and clever applied fixes.",
    Armorer: "You focus on protection, gear, defensive systems, wearable tech, and equipment that changes how people operate.",
    Artillerist: "You build controlled force. Your tools create impact, range, output, and pressure from a strategic position.",
    "Battle Smith": "You combine technical skill with practical conflict solving, companions, robotics, repair, and field ready engineering.",
    Cartographer: "You map systems, spaces, routes, networks, and unknown territory so people can move with confidence.",
  },
  Barbarian: {
    Berserker: "Your power is direct intensity, overwhelming action, and the ability to push through the wall when others freeze.",
    "Wild Heart": "Your intensity is tied to instinct, animal energy, wilderness, and a body first relationship with nature.",
    "World Tree": "You are a boundary keeper and protector who thinks in roots, networks, and people held together.",
    Zealot: "Your fury is attached to belief, mission, loyalty, or sacred purpose.",
  },
  Bard: {
    Dance: "You influence through movement, timing, rhythm, presence, and physical expression.",
    Glamour: "You use style, charm, fascination, and social magnetism to shape the room.",
    Lore: "You collect stories, facts, histories, references, and secrets, then use them to teach and influence.",
    Moon: "You blend healing, harm, emotion, rhythm, mystery, and changing phases of people and groups.",
    Valor: "You inspire through courage, heroic example, and performance under pressure.",
  },
  Cleric: {
    Knowledge: "You serve through truth, insight, teaching, wisdom, study, and helping people understand.",
    Life: "You are a direct healer, nurturer, restorer, and protector of wellbeing.",
    Light: "You bring hope, clarity, optimism, and force against darkness or despair.",
    Trickery: "You help through misdirection, cleverness, subversion, and changing how people see the problem.",
    War: "Your devotion becomes defense, conflict readiness, sacred action, and protection in hard moments.",
  },
  Druid: {
    Land: "You are place rooted, practical, environment aware, and connected to regions, seasons, and natural rhythms.",
    Moon: "You embody nature physically through animals, transformation, instinct, and changing forms.",
    Sea: "You are drawn to waves, storms, movement, pressure, emotion, and powerful natural flow.",
    Stars: "You seek guidance through patterns, cycles, navigation, long views, and cosmic perspective.",
  },
  Fighter: {
    Banneret: "You are a team captain who turns discipline into morale, coordination, and group performance.",
    "Battle Master": "You win through tactics, maneuvers, planning, precision, and controlled skill.",
    Champion: "You lean into athletic excellence, competition, clean execution, and physical dominance.",
    "Eldritch Knight": "You combine trained competence with study, technical systems, and specialized knowledge.",
    "Psi Warrior": "You apply willpower, perception, focus, and mental pressure to disciplined action.",
  },
  Monk: {
    Mercy: "Your discipline bends toward healing, restraint, ending suffering, and compassionate control.",
    Shadow: "You value stealth, silence, patience, unseen movement, and control from the margins.",
    Elements: "You express discipline through adaptable energy, nature force, motion, and controlled intensity.",
    "Open Hand": "You are direct martial discipline: clean technique, body control, and unarmed mastery.",
  },
  Paladin: {
    Devotion: "You embody law, justice, standards, purity, and classic oath keeping.",
    Glory: "You are driven by achievement, victory, ambition, and legend building.",
    Ancients: "You protect life, joy, nature, hope, and light against decay or despair.",
    "Noble Genies": "Your oath has grandeur, elemental style, patron like nobility, and a larger than life code.",
    Vengeance: "You pursue justice against wrongdoing and refuse to let serious harm go unanswered.",
  },
  Ranger: {
    "Beast Master": "You are defined by animal partnership, training, trust, and companionship with living allies.",
    "Fey Wanderer": "You blend charm, social wilderness, strange beauty, and an unusual presence.",
    "Gloom Stalker": "You hunt threats in darkness through patience, ambush, and quiet readiness.",
    Hunter: "You are the practical predator: traps, tactics, tracking, and classic hunting focus.",
    "Winter Walker": "You endure harsh environments, cold pressure, isolation, and discomfort without breaking.",
  },
  Rogue: {
    "Arcane Trickster": "You mix cleverness with technical misdirection, illusion, and strange problem solving.",
    Assassin: "You favor stealth, precision, patience, preparation, and decisive action.",
    "Scion of the Three": "Your edge is darker, intense, belief charged, and willing to become dangerous.",
    Soulknife: "Your precision is internal, mental, quiet, sharp, and hard for others to see coming.",
    Thief: "You are practical with tools, access, acquisition, movement, and hands on problem solving.",
  },
  Sorcerer: {
    "Aberrant Sorcery": "Your gift is strange perception, alien thought, mental weirdness, and unusual instincts.",
    "Clockwork Sorcery": "Your gift pushes toward order, balance, correction, structure, and mechanisms.",
    "Draconic Sorcery": "Your power feels inherited, proud, resilient, forceful, and naturally commanding.",
    "Spellfire Sorcery": "Your spark protects, flares, and channels raw energy in intense moments.",
    "Wild Magic Sorcery": "Your power is chaos, unpredictability, explosive instinct, and surprising turns.",
  },
  Warlock: {
    "Archfey Patron": "Your access comes through charm, glamour, trickery, strange social power, and fascination.",
    "Celestial Patron": "Your patronage bends toward healing, light, benevolent support, and service through granted power.",
    "Fiend Patron": "Your path is ambition, dangerous bargains, intensity, and power that comes with cost.",
    "Great Old One Patron": "Your access is forbidden knowledge, alien thought, hidden systems, and uncomfortable insight.",
  },
  Wizard: {
    Abjurer: "You specialize in prevention, defense, risk reduction, protection systems, and safe design.",
    Bladesinger: "You combine scholarship with elegant motion, precision, technical movement, and trained style.",
    Diviner: "You read patterns, forecast outcomes, compare signals, and prepare through insight.",
    Evoker: "You solve directly with focused output, high impact, and controlled force.",
    Illusionist: "You understand perception, framing, misdirection, presentation, and how people construct reality.",
  },
};

// Real-world "who you are" narrative templates. One per class.
// Placeholders: {facets}, {anchorHobbyLine}.
export const personalNarratives = {
  Artificer: "You think in systems and reach for tools the way other people reach for words. When something is broken, your hands start moving before your mouth does. What you build usually outlasts the moment that prompted it. {facets} {anchorHobbyLine}",
  Barbarian: "You don't pretend pressure isn't there. You walk straight into it. Your strength shows up loudest when everyone else is freezing, and a lot of people only realize how much they rely on that when you're not in the room. {facets} {anchorHobbyLine}",
  Bard: "You shape rooms. The way you talk, perform, or just exist in a group nudges energy in a direction, and you usually know which direction you're aiming for. {facets} {anchorHobbyLine}",
  Cleric: "You orient around care. Your time, attention, and patience flow toward whoever or whatever needs holding together, and you stay long after the dramatic helpers have moved on. {facets} {anchorHobbyLine}",
  Druid: "You're tuned to systems most people stop noticing. Where others see chaos you see cycles, and you treat the living world like something to be in relationship with, not just resource from. {facets} {anchorHobbyLine}",
  Fighter: "You believe in reps. Your confidence isn't a vibe. It's earned the slow way, drilled until the skill works whether or not you're nervous. {facets} {anchorHobbyLine}",
  Monk: "Your default move is to slow down. You regulate your own body and attention the way other people manage spreadsheets, and that quiet control is most of your edge. {facets} {anchorHobbyLine}",
  Paladin: "You move on commitment, not mood. When something matters, you don't negotiate yourself out of it. The people around you can feel where your lines are. {facets} {anchorHobbyLine}",
  Ranger: "You read terrain. Physical, social, situational. You catch the exit, the off-ramp, the threat, or the resource a few steps before anyone else does. {facets} {anchorHobbyLine}",
  Rogue: "You're allergic to the obvious path. Where most people see a wall you're already three steps into the side door, and you make limited information go a long way. {facets} {anchorHobbyLine}",
  Sorcerer: "Some of your strongest moves don't come from training. They come from somewhere you didn't have to build. People feel something land when you walk into a room, and you've learned to use it rather than apologize for it. {facets} {anchorHobbyLine}",
  Warlock: "You understand that power flows through people, networks, and access. Not just effort. You're skilled at being where the leverage actually lives. {facets} {anchorHobbyLine}",
  Wizard: "You think before you act, and you keep thinking longer than is comfortable for everyone else. By the time you're confident in a move, you've usually built a model of the whole system underneath it. {facets} {anchorHobbyLine}",
};

// Fantasy character narrative. One paragraph per class with a {subclassFlavor} slot.
// Optional {secondaryLine} for multiclass / strong secondary influence.
export const characterNarratives = {
  Artificer: "In the world, you'd be the one with a workshop louder than the tavern. Schematics on the walls, half-finished prototypes on every surface, and a satchel of contraptions that turn most ambushes into bad math. {subclassFlavor} Your party stops asking how you did it.",
  Barbarian: "On the road, you'd be the one between the party and whatever came out of the dark. People underestimate the precision in it. Your fury has a shape, and the people you're protecting can feel where its line is. {subclassFlavor} Your party trusts you with the heaviest moments.",
  Bard: "You'd be the voice in every village square. Somehow, by the end of the night, three new people have agreed to follow you somewhere they swore they'd never go. {subclassFlavor} Your party borrows your confidence on the bad days.",
  Cleric: "You'd be the steady one. The one who knows who's hurt, who hasn't eaten, who's losing their faith, and what each person actually needs even when they won't ask. {subclassFlavor} Your party would not have survived this far without you, and they know it.",
  Druid: "You'd be the one who notices the missing animal three days before the village does, and walks barefoot back from places no map admits exist. {subclassFlavor} Your party learns to trust your unease.",
  Fighter: "You'd be the trained edge of the group. The one who's drilled the move enough times that it works in the rain, in the dark, on a bad day. {subclassFlavor} When the plan dies, your party looks to you.",
  Monk: "You'd be the calm in the chaos. Where others wind up, you wind down. {subclassFlavor} Your party borrows your stillness to find their own.",
  Paladin: "You'd be the one whose word the party actually trusts. The one who said the thing out loud and then lived it. {subclassFlavor} People follow you because your code is visible from a distance.",
  Ranger: "You'd be ahead of the party most days. Scouting, listening, marking the route. They sleep easier because you don't. {subclassFlavor} Half their close calls are ones you cut off before they ever became close calls.",
  Rogue: "You'd be the one with three plans and a fourth one in reserve. Most threats never get to swing at you because you're already past them by the time they notice. {subclassFlavor} Your party stops asking how you got the key.",
  Sorcerer: "You'd be the one whose power doesn't come from a book. It pulses when you're angry, hums when you're calm, and gets loud when the party needs it to. {subclassFlavor} You spend half your time learning to aim it.",
  Warlock: "You'd be the one with the favor nobody else can call in. The contact, the patron, the contract that opens the gate. {subclassFlavor} Your party stops asking who you know.",
  Wizard: "You'd be the one with the worn book, the marginalia, and the three contingencies for the spell you haven't cast yet. {subclassFlavor} Your party leans on your preparation as much as your power.",
};

// Short subclass-specific flavor sentences inserted into character narratives.
// Fallback to "" if subclass not listed for that class.
export const characterSubclassPhrases = {
  Artificer: {
    Alchemist: "Your specialty: the right mixture, dose, or experiment exactly when it matters.",
    Armorer: "Your specialty: protection that changes how a fight actually goes.",
    Artillerist: "Your specialty: bringing force from a place the enemy didn't think to watch.",
    "Battle Smith": "Your specialty: built companions and repairs done mid-fight.",
    Cartographer: "Your specialty: knowing where the road actually goes, and where it doesn't.",
  },
  Barbarian: {
    Berserker: "Your specialty: pure intensity at the moment of impact.",
    "Wild Heart": "Your specialty: a body-first connection to instinct and animal energy.",
    "World Tree": "Your specialty: holding the line for everyone behind you.",
    Zealot: "Your specialty: belief that doesn't quit, even when the body should.",
  },
  Bard: {
    Dance: "Your specialty: moving the room before the words land.",
    Glamour: "Your specialty: charm that people can't quite remember resisting.",
    Lore: "Your specialty: the story, the reference, the fact that closes the argument.",
    Moon: "Your specialty: shifting moods like phases. Knowing exactly when to break the room and when to mend it.",
    Valor: "Your specialty: heroic example under pressure, so other people find their nerve.",
  },
  Cleric: {
    Knowledge: "Your specialty: the truth told gently enough that someone can actually receive it.",
    Life: "Your specialty: restoring people, one quiet act at a time.",
    Light: "Your specialty: hope that costs you something, but doesn't break.",
    Trickery: "Your specialty: bending the situation sideways so the right person wins.",
    War: "Your specialty: sacred readiness. Care that includes the willingness to fight for it.",
  },
  Druid: {
    Land: "Your specialty: deep knowledge of the place you actually live in.",
    Moon: "Your specialty: shifting forms. Instinct made physical.",
    Sea: "Your specialty: working with storms instead of against them.",
    Stars: "Your specialty: long views and pattern reading no one else stops to do.",
  },
  Fighter: {
    Banneret: "Your specialty: lifting everyone around you a level above where they'd be alone.",
    "Battle Master": "Your specialty: maneuvers and tactics most people don't see coming.",
    Champion: "Your specialty: clean execution under stakes.",
    "Eldritch Knight": "Your specialty: trained edge plus the deep knowledge to back it up.",
    "Psi Warrior": "Your specialty: willpower as a weapon. Focus that bends the moment.",
  },
  Monk: {
    Mercy: "Your specialty: ending suffering with control, not collateral.",
    Shadow: "Your specialty: stillness so complete the moment moves around you.",
    Elements: "Your specialty: adaptable energy. Water one breath, fire the next.",
    "Open Hand": "Your specialty: clean technique, body as the only weapon you need.",
  },
  Paladin: {
    Devotion: "Your specialty: an oath you keep when nobody is watching.",
    Glory: "Your specialty: turning ambition into something other people can rally behind.",
    Ancients: "Your specialty: standing for light, joy, and the living world.",
    "Noble Genies": "Your specialty: a code with grandeur. Elemental, larger than personal.",
    Vengeance: "Your specialty: pursuing what was done, until it's answered.",
  },
  Ranger: {
    "Beast Master": "Your specialty: partnership with a creature that trusts you completely.",
    "Fey Wanderer": "Your specialty: charm shaped by wilderness. Strange, beautiful, hard to place.",
    "Gloom Stalker": "Your specialty: hunting in the dark, where the threat doesn't see you first.",
    Hunter: "Your specialty: traps, tactics, and the long patient watch.",
    "Winter Walker": "Your specialty: enduring conditions other people quit in.",
  },
  Rogue: {
    "Arcane Trickster": "Your specialty: misdirection that bends what people think they saw.",
    Assassin: "Your specialty: one decisive moment, prepared and precise.",
    "Scion of the Three": "Your specialty: belief sharp enough to cut, even when it costs.",
    Soulknife: "Your specialty: an internal edge nobody can see coming.",
    Thief: "Your specialty: hands, tools, and the right object at the right moment.",
  },
  Sorcerer: {
    "Aberrant Sorcery": "Your specialty: alien perception. You see what others can't quite reach.",
    "Clockwork Sorcery": "Your specialty: order and correction. Your gift fixes what's drifting.",
    "Draconic Sorcery": "Your specialty: inherited presence. Pride and resilience that command space.",
    "Spellfire Sorcery": "Your specialty: protective fire. Your power flares for the people you love.",
    "Wild Magic Sorcery": "Your specialty: chaos. Luck and surprise the table didn't see coming.",
  },
  Warlock: {
    "Archfey Patron": "Your specialty: charm and glamour with a wilder edge.",
    "Celestial Patron": "Your specialty: granted light. Power lent to you for service.",
    "Fiend Patron": "Your specialty: a bargain with cost, and the will to make it pay.",
    "Great Old One Patron": "Your specialty: knowing things you probably shouldn't, and using it anyway.",
  },
  Wizard: {
    Abjurer: "Your specialty: prevention. The bad thing that never quite happens.",
    Bladesinger: "Your specialty: scholarship in motion. Elegance with a blade.",
    Diviner: "Your specialty: reading what's coming before it arrives.",
    Evoker: "Your specialty: focused force. The spell that ends the fight.",
    Illusionist: "Your specialty: framing reality so the truth bends to fit it.",
  },
};

// Growth / stretch tips. One per class with optional subclass-aware override.
export const growthTips = {
  Artificer: { headline: "Stretch toward documenting the why, not just the build.", body: "You finish working things. The next level is leaving a trail other people can pick up. Diagrams, runbooks, a write-up. That's where Artificer leans into Wizard." },
  Barbarian: { headline: "Stretch toward training the recovery, not just the surge.", body: "You bring intensity. The next level is what you do twenty minutes after. Breath, sleep, repair. Borrow from Monk." },
  Bard: { headline: "Stretch toward writing it down.", body: "You shape rooms live. The next level is shaping rooms you're not in. Essays, talks, content with a longer half-life. Borrow from Wizard." },
  Cleric: { headline: "Stretch toward letting people sit with their own thing.", body: "You hold people well. The next level is trusting them to carry more. Your care is most powerful when it's not also doing their work for them." },
  Druid: { headline: "Stretch toward making your knowledge legible.", body: "You see the system. The next level is teaching one other person to see it too. Guided walks, journaling, a project that brings a friend into your eye." },
  Fighter: { headline: "Stretch toward coaching, not just performing.", body: "You drill until it works. The next level is making your reps reproducible for someone else. That's where Fighter leans into Banneret." },
  Monk: { headline: "Stretch toward applying the calm outside the practice.", body: "You regulate beautifully in your own space. The next level is bringing that same quality into the messiest interpersonal moments." },
  Paladin: { headline: "Stretch toward staying flexible inside the commitment.", body: "Your line is clear. The next level is letting tactics flex without the principle flexing. Borrow from Rogue for the side route." },
  Ranger: { headline: "Stretch toward staying in the camp longer.", body: "You're built for the field. The next level is the relational work that holds the party together when the trail's done. Borrow from Cleric." },
  Rogue: { headline: "Stretch toward building one durable thing.", body: "You're great with workarounds. The next level is letting one of those workarounds become a real system that doesn't need you. That's where Rogue leans into Artificer." },
  Sorcerer: { headline: "Stretch toward studying what already works for you.", body: "Your gift is real. The next level is naming the mechanics underneath it so you can hit it on demand, not by luck. Borrow from Wizard." },
  Warlock: { headline: "Stretch toward building skill the patron can't grant.", body: "Your access is real leverage. The next level is making sure your own craft holds up when the favor isn't there. Borrow from Fighter." },
  Wizard: { headline: "Stretch toward putting it out before it's perfect.", body: "Your prep is rare. The next level is letting a working draft out the door earlier. Borrow from Artificer." },
};
