// Class visual + descriptive metadata. Lifted from v2 file unchanged.

export const classData = {
  Artificer: {
    color: "bg-[#d85a24] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#8e2c1a]",
    motto: "Power through tools, invention, repair, and applied systems.",
    summary: "You turn ideas into working things. You build, automate, repair, prototype, script, engineer, and make abstract knowledge usable in the real world.",
    traits: ["Tool Builder", "Applied Technical", "Prototype Mind"],
  },
  Barbarian: {
    color: "bg-[#c7381d] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#8e2c1a]",
    motto: "Power through pressure, instinct, and raw courage.",
    summary: "You are at your strongest when the situation gets intense. You move toward pressure instead of away from it, and your strength is protective, emotional, and immediate.",
    traits: ["Pressure Brave", "Protective Force", "Explosive Energy"],
  },
  Bard: {
    color: "bg-[#ef7a32] text-[#171717] border-[#0b0b0b]",
    accent: "text-[#c7381d]",
    motto: "Power through expression, influence, and shared emotion.",
    summary: "You change the room. Through humor, music, teaching, storytelling, performance, or social skill, your gift is turning attention into momentum.",
    traits: ["Story Shaper", "Social Spark", "Creative Influence"],
  },
  Cleric: {
    color: "bg-[#fff2cf] text-[#171717] border-[#0b0b0b]",
    accent: "text-[#d85a24]",
    motto: "Power through devotion, service, and sacred responsibility.",
    summary: "You are driven by care, calling, and service. Your strength comes from helping people heal, endure, and reconnect with something larger than themselves.",
    traits: ["Community Healer", "Devoted Guide", "Steady Light"],
  },
  Druid: {
    color: "bg-[#168a32] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#0d5521]",
    motto: "Power through nature, balance, and living systems.",
    summary: "You feel oriented by nature and living systems. Your instincts lean toward stewardship, ecology, animals, plants, cycles, and balance.",
    traits: ["Nature Bound", "Balance Keeper", "Living Systems Mind"],
  },
  Fighter: {
    color: "bg-[#727a78] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#4d5554]",
    motto: "Power through training, discipline, and repeatable skill.",
    summary: "You respect craft. You build competence through drills, systems, tools, and practice until your skill works under pressure.",
    traits: ["Trained Operator", "Tactical Builder", "Reliable Specialist"],
  },
  Monk: {
    color: "bg-[#f1c4a8] text-[#171717] border-[#0b0b0b]",
    accent: "text-[#d85a24]",
    motto: "Power through discipline, body control, and inner focus.",
    summary: "You are strongest when body and mind work together. Your path is discipline, self regulation, martial practice, breath, restraint, and focused repetition.",
    traits: ["Body Mind Discipline", "Calm Under Strain", "Focused Practice"],
  },
  Paladin: {
    color: "bg-[#8ddfd6] text-[#171717] border-[#0b0b0b]",
    accent: "text-[#2e7f82]",
    motto: "Power through oath, duty, and moral action.",
    summary: "You are not just motivated. You are committed. Your identity sharpens around causes, promises, standards, and action when something important is on the line.",
    traits: ["Oath Driven", "Moral Protector", "Mission Leader"],
  },
  Ranger: {
    color: "bg-[#0d5521] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#168a32]",
    motto: "Power through fieldcraft, tracking, and practical independence.",
    summary: "You are observant, practical, and comfortable operating away from the crowd. You notice terrain, patterns, movement, risks, and resources before others do.",
    traits: ["Field Ready", "Quiet Watcher", "Practical Survivor"],
  },
  Rogue: {
    color: "bg-[#2b2f31] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#727a78]",
    motto: "Power through cunning, precision, and alternate routes.",
    summary: "You solve problems by seeing the side door. You are precise, adaptive, skeptical of obvious paths, and good at turning limited information into advantage.",
    traits: ["Side Door Thinker", "Precision Mover", "Information Edge"],
  },
  Sorcerer: {
    color: "bg-[#8e2c1a] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#c7381d]",
    motto: "Power through innate gift, charisma, and natural force.",
    summary: "Some of what you do well seems to come naturally. You often rely on instinct, presence, raw aptitude, or personal magnetism before formal systems catch up.",
    traits: ["Natural Talent", "Raw Spark", "Instinctive Power"],
  },
  Warlock: {
    color: "bg-[#4d5554] text-[#fff2cf] border-[#0b0b0b]",
    accent: "text-[#2b2f31]",
    motto: "Power through patronage, leverage, and rare access.",
    summary: "You understand that power often comes through networks, institutions, sponsors, mentors, contracts, platforms, and access. You are good at using leverage others overlook.",
    traits: ["Patron Linked", "Access Broker", "Leverage Mind"],
  },
  Wizard: {
    color: "bg-[#c5cbc7] text-[#171717] border-[#0b0b0b]",
    accent: "text-[#2e7f82]",
    motto: "Power through study, systems, and documented mastery.",
    summary: "You turn knowledge into capability. You research, document, compare, prepare, and build mental models until a confusing problem becomes a usable system.",
    traits: ["Scholar Builder", "Systems Thinker", "Prepared Mind"],
  },
};

export const scoreBarColors = {
  Artificer: "bg-[#d85a24]",
  Barbarian: "bg-[#c7381d]",
  Bard: "bg-[#ef7a32]",
  Cleric: "bg-[#fff2cf]",
  Druid: "bg-[#168a32]",
  Fighter: "bg-[#727a78]",
  Monk: "bg-[#f1c4a8]",
  Paladin: "bg-[#8ddfd6]",
  Ranger: "bg-[#0d5521]",
  Rogue: "bg-[#2b2f31]",
  Sorcerer: "bg-[#8e2c1a]",
  Warlock: "bg-[#4d5554]",
  Wizard: "bg-[#c5cbc7]",
};

export const classIconSrc = {
  Artificer: "/class-icons/artificer.png",
  Barbarian: "/class-icons/barbarian.png",
  Bard: "/class-icons/bard.png",
  Cleric: "/class-icons/cleric.png",
  Druid: "/class-icons/druid.png",
  Fighter: "/class-icons/fighter.png",
  Monk: "/class-icons/monk.png",
  Paladin: "/class-icons/paladin.png",
  Ranger: "/class-icons/ranger.png",
  Rogue: "/class-icons/rogue.png",
  Sorcerer: "/class-icons/sorcerer.png",
  Warlock: "/class-icons/warlock.png",
  Wizard: "/class-icons/wizard.png",
};

export const subclassData = {
  Artificer: {
    Alchemist: "You transform problems through experiments, mixtures, chemistry, support, and clever applied fixes.",
    Armorer: "You focus on protection, gear, defensive systems, wearable tech, and equipment that changes how people operate.",
    Artillerist: "You build controlled force. Your tools create impact, range, output, and pressure from a strategic position.",
    "Battle Smith": "You combine technical skill with practical conflict solving, companions, robotics, repair, and field ready engineering.",
    Cartographer: "You map systems, spaces, routes, networks, and unknown territory so people can move with confidence.",
  },
  Barbarian: {
    Berserker: "Your power is direct intensity, overwhelming action, and the ability to push through the wall when others freeze.",
    "Wild Heart": "Your intensity is tied to instinct, animal energy, wilderness, and a body first relationship with nature.",
    "World Tree": "You are a boundary keeper and protector who thinks in roots, networks, and people held together.",
    Zealot: "Your fury is attached to belief, mission, loyalty, or sacred purpose.",
  },
  Bard: {
    Dance: "You influence through movement, timing, rhythm, presence, and physical expression.",
    Glamour: "You use style, charm, fascination, and social magnetism to shape the room.",
    Lore: "You collect stories, facts, histories, references, and secrets, then use them to teach and influence.",
    Moon: "You blend healing, harm, emotion, rhythm, mystery, and changing phases of people and groups.",
    Valor: "You inspire through courage, heroic example, and performance under pressure.",
  },
  Cleric: {
    Knowledge: "You serve through truth, insight, teaching, wisdom, study, and helping people understand.",
    Life: "You are a direct healer, nurturer, restorer, and protector of wellbeing.",
    Light: "You bring hope, clarity, optimism, and force against darkness or despair.",
    Trickery: "You help through misdirection, cleverness, subversion, and changing how people see the problem.",
    War: "Your devotion becomes defense, conflict readiness, sacred action, and protection in hard moments.",
  },
  Druid: {
    Land: "You are place rooted, practical, environment aware, and connected to regions, seasons, and natural rhythms.",
    Moon: "You embody nature physically through animals, transformation, instinct, and changing forms.",
    Sea: "You are drawn to waves, storms, movement, pressure, emotion, and powerful natural flow.",
    Stars: "You seek guidance through patterns, cycles, navigation, long views, and cosmic perspective.",
  },
  Fighter: {
    Banneret: "You are a team captain who turns discipline into morale, coordination, and group performance.",
    "Battle Master": "You win through tactics, maneuvers, planning, precision, and controlled skill.",
    Champion: "You lean into athletic excellence, competition, clean execution, and physical dominance.",
    "Eldritch Knight": "You combine trained competence with study, technical systems, and specialized knowledge.",
    "Psi Warrior": "You apply willpower, perception, focus, and mental pressure to disciplined action.",
  },
  Monk: {
    Mercy: "Your discipline bends toward healing, restraint, ending suffering, and compassionate control.",
    Shadow: "You value stealth, silence, patience, unseen movement, and control from the margins.",
    Elements: "You express discipline through adaptable energy, nature force, motion, and controlled intensity.",
    "Open Hand": "You are direct martial discipline: clean technique, body control, and unarmed mastery.",
  },
  Paladin: {
    Devotion: "You embody law, justice, standards, purity, and classic oath keeping.",
    Glory: "You are driven by achievement, victory, ambition, and legend building.",
    Ancients: "You protect life, joy, nature, hope, and light against decay or despair.",
    "Noble Genies": "Your oath has grandeur, elemental style, patron like nobility, and a larger than life code.",
    Vengeance: "You pursue justice against wrongdoing and refuse to let serious harm go unanswered.",
  },
  Ranger: {
    "Beast Master": "You are defined by animal partnership, training, trust, and companionship with living allies.",
    "Fey Wanderer": "You blend charm, social wilderness, strange beauty, and an unusual presence.",
    "Gloom Stalker": "You hunt threats in darkness through patience, ambush, and quiet readiness.",
    Hunter: "You are the practical predator: traps, tactics, tracking, and classic hunting focus.",
    "Winter Walker": "You endure harsh environments, cold pressure, isolation, and discomfort without breaking.",
  },
  Rogue: {
    "Arcane Trickster": "You mix cleverness with technical misdirection, illusion, and strange problem solving.",
    Assassin: "You favor stealth, precision, patience, preparation, and decisive action.",
    "Scion of the Three": "Your edge is darker, intense, belief charged, and willing to become dangerous.",
    Soulknife: "Your precision is internal, mental, quiet, sharp, and hard for others to see coming.",
    Thief: "You are practical with tools, access, acquisition, movement, and hands on problem solving.",
  },
  Sorcerer: {
    "Aberrant Sorcery": "Your gift is strange perception, alien thought, mental weirdness, and unusual instincts.",
    "Clockwork Sorcery": "Your gift pushes toward order, balance, correction, structure, and mechanisms.",
    "Draconic Sorcery": "Your power feels inherited, proud, resilient, forceful, and naturally commanding.",
    "Spellfire Sorcery": "Your spark protects, flares, and channels raw energy in intense moments.",
    "Wild Magic Sorcery": "Your power is chaos, unpredictability, explosive instinct, and surprising turns.",
  },
  Warlock: {
    "Archfey Patron": "Your access comes through charm, glamour, trickery, strange social power, and fascination.",
    "Celestial Patron": "Your patronage bends toward healing, light, benevolent support, and service through granted power.",
    "Fiend Patron": "Your path is ambition, dangerous bargains, intensity, and power that comes with cost.",
    "Great Old One Patron": "Your access is forbidden knowledge, alien thought, hidden systems, and uncomfortable insight.",
  },
  Wizard: {
    Abjurer: "You specialize in prevention, defense, risk reduction, protection systems, and safe design.",
    Bladesinger: "You combine scholarship with elegant motion, precision, technical movement, and trained style.",
    Diviner: "You read patterns, forecast outcomes, compare signals, and prepare through insight.",
    Evoker: "You solve directly with focused output, high impact, and controlled force.",
    Illusionist: "You understand perception, framing, misdirection, presentation, and how people construct reality.",
  },
};
