// Short behavioral blurbs for each trait shown on the result page.
// Surfaced under the trait name so users understand *why* the test tagged them
// with that signal rather than seeing a bare label like "Builder" or "Scholar".
// Keep each line under ~70 chars; plain English, no D&D jargon.

export const facetBlurbs = {
  // --- Answer-tag facets (from src/questions_v3.mjs) ---
  "Access Aware": "Knows who controls what and routes through them.",
  "Access Broker": "Connects the people who need each other.",
  "Access Solver": "Opens doors others assumed were locked.",
  "Alien Insight": "Sees angles most people miss entirely.",
  "Animal Embodied": "Moves on instinct, not technique.",
  "Animal Partner": "Works through a bond with creatures.",
  "Automation Mind": "Sets up systems so problems stop recurring.",
  "Body Mind": "Trains body and mind as one practice.",
  "Boundary Keep": "Holds the line others would cross.",
  "Builder": "Fixes the system, not the symptom.",
  "Calm Under Strain": "Gets quieter as pressure rises.",
  "Cause Fury": "Anger that aims, not anger that scatters.",
  "Cause Led": "Moves for the mission before the self.",
  "Charm Path": "Wins rooms before fighting them.",
  "Cold Endurance": "Outlasts conditions others tap out of.",
  "Commander": "Others fall into your formation naturally.",
  "Commanding": "Voice that organizes a room.",
  "Community Healer": "Tends the group, not just the patient.",
  "Companion Build": "Strongest paired with a partner.",
  "Compassionate Discipline": "Soft heart, hard practice.",
  "Compassionate": "Leads with care first.",
  "Competitor": "Sharpens against real opponents.",
  "Connected": "Pulls help through your network.",
  "Connector": "Bridges people on their behalf.",
  "Coordinator": "Turns a crowd into a unit.",
  "Costly Ambition": "Pays a high price for what you want.",
  "Crafted Influence": "Persuasion you actually designed.",
  "Credentialed": "Earns the paper, not just the skill.",
  "Dark Edge": "Willing to use the ugly option.",
  "Dark Hunter": "Pursues with cold intent.",
  "Design Analyst": "Reads the structure under the surface.",
  "Devotion": "Keeps the vow past convenience.",
  "Direct Force": "Meets the problem head-on.",
  "Disciplined": "Same reps, every day.",
  "Documented": "Writes it down before doing it.",
  "Elegant Precision": "Clean motion, no waste.",
  "Elemental Flow": "Moves with the current, not against it.",
  "Emotional Tide": "Feelings as fuel and weather.",
  "Endurer": "Last one still standing.",
  "Experimenter": "Tries it to find out.",
  "Exploit Finder": "Spots the gap in the rules.",
  "Expressive Movement": "Body talks louder than words.",
  "Fascinating Access": "Pulls strange doors open.",
  "Fey Presence": "Unsettling charisma you can't quite place.",
  "Field Credentialed": "Credentials earned on the ground.",
  "Fieldcraft": "At home in terrain others fear.",
  "Fix Builder": "Repairs that hold past the moment.",
  "Forbidden Insight": "Knows what shouldn't be known.",
  "Force Multiplier": "Makes the team hit harder.",
  "Glory": "Chases the high-stakes moment.",
  "Grand Oath": "Promises that bind years out.",
  "Granted Light": "Borrowed power, used with care.",
  "Grit": "Finishes through the part that hurts.",
  "Hands On": "Learns by doing, not reading.",
  "Healer": "Fixes people, not just problems.",
  "Heroic Voice": "Voice that rallies others.",
  "High Impact": "Swings hard, lands hard.",
  "Hunter": "Closes the distance and finishes.",
  "Improviser": "Solves it with what's on the table.",
  "Influencer": "Shifts opinion without forcing it.",
  "Instinct Body": "Body decides before mind catches up.",
  "Instinctive": "Moves first, explains later.",
  "Land Steward": "Protects the place that raised you.",
  "Leverage": "Small inputs, big shifts.",
  "Light Bearer": "Carries hope into dark rooms.",
  "Light Protector": "Guards the vulnerable spot.",
  "Living Systems Mind": "Thinks in ecology, not parts.",
  "Lore Keeper": "Remembers what the group forgot.",
  "Magnetic": "People drift toward you.",
  "Maker Evidence": "Proof in the thing you made.",
  "Maker": "Builds the artifact that solves it.",
  "Mapper": "Turns chaos into legible terrain.",
  "Measured Growth": "Improves at a sustainable pace.",
  "Mental Edge": "Sharper thinking under pressure.",
  "Mental Force": "Moves people through sheer focus.",
  "Mentor Linked": "Learns through someone you respect.",
  "Misdirection": "Wins by pointing elsewhere.",
  "Moral Backbone": "Won't bend on what matters.",
  "Morale Keeper": "Holds the group's spirit up.",
  "Natural Presence": "Confidence without rehearsal.",
  "Observer": "Sees before acting.",
  "Orderly Force": "Power inside a system.",
  "Output Build": "Builds for the result, not the show.",
  "Patch Builder": "Ships the fix while the clock ticks.",
  "Patron Linked": "Power borrowed from a deal.",
  "Patronage": "Leverages relationships up the chain.",
  "Pattern Navigator": "Moves through complexity by feel.",
  "Pattern Reader": "Sees the shape before others do.",
  "Permanent Fix": "Solves it so it stops returning.",
  "Place Rooted": "Anchored to a specific ground.",
  "Power Trained": "Strength refined by drill.",
  "Practice Based": "Earns it through reps.",
  "Precision": "Tight tolerances, every time.",
  "Prepared": "Already thought it through.",
  "Pressure Brave": "Bigger as the stakes climb.",
  "Prevention": "Kills the problem before it lands.",
  "Principled": "Runs decisions through a code.",
  "Process Trainer": "Teaches the how, not the answer.",
  "Protective Spark": "Defends what's fragile.",
  "Protector Build": "Designs to shield others.",
  "Protector": "Body between threat and friend.",
  "Public Voice": "Speaks where many can hear.",
  "Pure Force": "Raw, no apology.",
  "Pure Technique": "Form over force.",
  "Reality Framer": "Names what's happening, changes it.",
  "Reflective Mover": "Moves with thought behind it.",
  "Reflective": "Pauses to understand first.",
  "Restorer": "Brings things back to working order.",
  "Rhythm": "Finds the beat in chaos.",
  "Root Cause": "Chases the why under the what.",
  "Rule Bender": "Bends rules to keep the intent.",
  "Sacred Warrior": "Fights for something larger than self.",
  "Scholar": "Books before action.",
  "Scout": "First eyes on the ground.",
  "Self Mastery": "Controls self before others.",
  "Self Reliant": "Fixes own problems first.",
  "Self Studied": "Taught yourself.",
  "Service First": "Others before self.",
  "Service Led": "Moves to serve, not to win.",
  "Smart Hack": "Clever shortcut, not a lazy one.",
  "Standard Bearer": "Carries the symbol others follow.",
  "Steward": "Keeps it healthy for the next round.",
  "Storm Heart": "Calm in the gust.",
  "Strategist": "Plans the whole arc.",
  "Subverter": "Flips the frame.",
  "Sustainer": "Keeps the engine running.",
  "System Support": "Strengthens what others use.",
  "Tactical": "Right move for the moment.",
  "Tactician": "Sees three moves ahead.",
  "Team Captain": "Leads from inside the group.",
  "Tool Maker": "Builds the thing that does the work.",
  "Tracker": "Follows trace others miss.",
  "Trained Scholar": "Practice plus study.",
  "Truth Seeker": "Wants the real answer, not comfort.",
  "Unseen Operator": "Works where you can't see them.",
  "Vengeance": "Settles what was owed.",
  "Wild Card": "Unpredictable on purpose.",
  "Workaround Mind": "Routes around obstacles by default.",
  "Workaround": "Finds the side path.",

  // --- Class fallback traits (from classMetadata_v3.mjs) ---
  // Used when the user produced no facet tags (rare, but possible).
  "Tool Builder": "Engineers the device that does the job.",
  "Applied Technical": "Technical chops aimed at real problems.",
  "Prototype Mind": "Iterates rough until it works.",
  "Protective Force": "Power pointed at protecting others.",
  "Explosive Energy": "Releases all at once when needed.",
  "Story Shaper": "Shapes how people see what happened.",
  "Social Spark": "Starts the room moving.",
  "Creative Influence": "Moves people through the work you make.",
  "Devoted Guide": "Walks others through the dark patches.",
  "Steady Light": "Doesn't flicker when others do.",
  "Nature Bound": "Lives close to natural rhythm.",
  "Balance Keeper": "Holds the middle so the system doesn't tip.",
  "Trained Operator": "Drilled until the move is automatic.",
  "Tactical Builder": "Builds gear matched to the mission.",
  "Reliable Specialist": "The one to call for this exact job.",
  "Body Mind Discipline": "Trains body and mind together.",
  "Focused Practice": "Narrow reps, deep mastery.",
  "Oath Driven": "The promise drives the action.",
  "Moral Protector": "Guards what's right, not what's easy.",
  "Mission Leader": "Leads through the mission, not the title.",
  "Field Ready": "Drops in and operates.",
  "Quiet Watcher": "Sees more by saying less.",
  "Practical Survivor": "Ends each day still standing.",
  "Side Door Thinker": "Finds the entrance no one watched.",
  "Precision Mover": "Small, exact actions, big effect.",
  "Information Edge": "Wins because you knew first.",
  "Natural Talent": "Good before you tried.",
  "Raw Spark": "The gift before the training.",
  "Instinctive Power": "Power that arrives, not power that's built.",
  "Leverage Mind": "Thinks in points where small moves shift big ones.",
  "Scholar Builder": "Studies the thing, then builds it.",
  "Systems Thinker": "Sees parts as a whole.",
  "Prepared Mind": "Already thought it through before you asked.",
};

export function getFacetBlurb(trait) {
  return facetBlurbs[trait] || "";
}
